// api/proto/gomoku.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.36.1
// source: api/proto/gomoku.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GomokuService_PlayStream_FullMethodName = "/pb.GomokuService/PlayStream"
)

// GomokuServiceClient is the client API for GomokuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GomokuServiceClient interface {
	// Bi-directional Streaming RPC
	PlayStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientAction, GameSync], error)
}

type gomokuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGomokuServiceClient(cc grpc.ClientConnInterface) GomokuServiceClient {
	return &gomokuServiceClient{cc}
}

func (c *gomokuServiceClient) PlayStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientAction, GameSync], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GomokuService_ServiceDesc.Streams[0], GomokuService_PlayStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientAction, GameSync]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GomokuService_PlayStreamClient = grpc.BidiStreamingClient[ClientAction, GameSync]

// GomokuServiceServer is the server API for GomokuService service.
// All implementations must embed UnimplementedGomokuServiceServer
// for forward compatibility.
type GomokuServiceServer interface {
	// Bi-directional Streaming RPC
	PlayStream(grpc.BidiStreamingServer[ClientAction, GameSync]) error
	mustEmbedUnimplementedGomokuServiceServer()
}

// UnimplementedGomokuServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGomokuServiceServer struct{}

func (UnimplementedGomokuServiceServer) PlayStream(grpc.BidiStreamingServer[ClientAction, GameSync]) error {
	return status.Error(codes.Unimplemented, "method PlayStream not implemented")
}
func (UnimplementedGomokuServiceServer) mustEmbedUnimplementedGomokuServiceServer() {}
func (UnimplementedGomokuServiceServer) testEmbeddedByValue()                       {}

// UnsafeGomokuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GomokuServiceServer will
// result in compilation errors.
type UnsafeGomokuServiceServer interface {
	mustEmbedUnimplementedGomokuServiceServer()
}

func RegisterGomokuServiceServer(s grpc.ServiceRegistrar, srv GomokuServiceServer) {
	// If the following call panics, it indicates UnimplementedGomokuServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GomokuService_ServiceDesc, srv)
}

func _GomokuService_PlayStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GomokuServiceServer).PlayStream(&grpc.GenericServerStream[ClientAction, GameSync]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GomokuService_PlayStreamServer = grpc.BidiStreamingServer[ClientAction, GameSync]

// GomokuService_ServiceDesc is the grpc.ServiceDesc for GomokuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GomokuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GomokuService",
	HandlerType: (*GomokuServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PlayStream",
			Handler:       _GomokuService_PlayStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/gomoku.proto",
}
