// api/proto/gomoku.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: api/proto/gomoku.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Host -> Client (Đồng bộ GameState)
type GameSync struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	CurrentTurn      int32                  `protobuf:"varint,2,opt,name=current_turn,json=currentTurn,proto3" json:"current_turn,omitempty"`
	Winner           int32                  `protobuf:"varint,3,opt,name=winner,proto3" json:"winner,omitempty"`
	Board            []*BoardRow            `protobuf:"bytes,4,rep,name=board,proto3" json:"board,omitempty"`
	WinningPositions []*Position            `protobuf:"bytes,5,rep,name=winning_positions,json=winningPositions,proto3" json:"winning_positions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameSync) Reset() {
	*x = GameSync{}
	mi := &file_api_proto_gomoku_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSync) ProtoMessage() {}

func (x *GameSync) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gomoku_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSync.ProtoReflect.Descriptor instead.
func (*GameSync) Descriptor() ([]byte, []int) {
	return file_api_proto_gomoku_proto_rawDescGZIP(), []int{0}
}

func (x *GameSync) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GameSync) GetCurrentTurn() int32 {
	if x != nil {
		return x.CurrentTurn
	}
	return 0
}

func (x *GameSync) GetWinner() int32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

func (x *GameSync) GetBoard() []*BoardRow {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GameSync) GetWinningPositions() []*Position {
	if x != nil {
		return x.WinningPositions
	}
	return nil
}

type BoardRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []byte                 `protobuf:"bytes,1,opt,name=cells,proto3" json:"cells,omitempty"` // bytes map 1-1 cực tốt với []uint8 trong Go
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardRow) Reset() {
	*x = BoardRow{}
	mi := &file_api_proto_gomoku_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardRow) ProtoMessage() {}

func (x *BoardRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gomoku_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardRow.ProtoReflect.Descriptor instead.
func (*BoardRow) Descriptor() ([]byte, []int) {
	return file_api_proto_gomoku_proto_rawDescGZIP(), []int{1}
}

func (x *BoardRow) GetCells() []byte {
	if x != nil {
		return x.Cells
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_api_proto_gomoku_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gomoku_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_api_proto_gomoku_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Client -> Host (Gửi hành động)
type ClientAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "move" hoặc "restart"
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAction) Reset() {
	*x = ClientAction{}
	mi := &file_api_proto_gomoku_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAction) ProtoMessage() {}

func (x *ClientAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gomoku_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAction.ProtoReflect.Descriptor instead.
func (*ClientAction) Descriptor() ([]byte, []int) {
	return file_api_proto_gomoku_proto_rawDescGZIP(), []int{3}
}

func (x *ClientAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClientAction) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ClientAction) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_api_proto_gomoku_proto protoreflect.FileDescriptor

const file_api_proto_gomoku_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/gomoku.proto\x12\x02pb\"\xb8\x01\n" +
	"\bGameSync\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\fcurrent_turn\x18\x02 \x01(\x05R\vcurrentTurn\x12\x16\n" +
	"\x06winner\x18\x03 \x01(\x05R\x06winner\x12\"\n" +
	"\x05board\x18\x04 \x03(\v2\f.pb.BoardRowR\x05board\x129\n" +
	"\x11winning_positions\x18\x05 \x03(\v2\f.pb.PositionR\x10winningPositions\" \n" +
	"\bBoardRow\x12\x14\n" +
	"\x05cells\x18\x01 \x01(\fR\x05cells\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\">\n" +
	"\fClientAction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y2A\n" +
	"\rGomokuService\x120\n" +
	"\n" +
	"PlayStream\x12\x10.pb.ClientAction\x1a\f.pb.GameSync(\x010\x01B.Z,github.com/ttasc/gotermoku/internal/netio/pbb\x06proto3"

var (
	file_api_proto_gomoku_proto_rawDescOnce sync.Once
	file_api_proto_gomoku_proto_rawDescData []byte
)

func file_api_proto_gomoku_proto_rawDescGZIP() []byte {
	file_api_proto_gomoku_proto_rawDescOnce.Do(func() {
		file_api_proto_gomoku_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_gomoku_proto_rawDesc), len(file_api_proto_gomoku_proto_rawDesc)))
	})
	return file_api_proto_gomoku_proto_rawDescData
}

var file_api_proto_gomoku_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_gomoku_proto_goTypes = []any{
	(*GameSync)(nil),     // 0: pb.GameSync
	(*BoardRow)(nil),     // 1: pb.BoardRow
	(*Position)(nil),     // 2: pb.Position
	(*ClientAction)(nil), // 3: pb.ClientAction
}
var file_api_proto_gomoku_proto_depIdxs = []int32{
	1, // 0: pb.GameSync.board:type_name -> pb.BoardRow
	2, // 1: pb.GameSync.winning_positions:type_name -> pb.Position
	3, // 2: pb.GomokuService.PlayStream:input_type -> pb.ClientAction
	0, // 3: pb.GomokuService.PlayStream:output_type -> pb.GameSync
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_gomoku_proto_init() }
func file_api_proto_gomoku_proto_init() {
	if File_api_proto_gomoku_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_gomoku_proto_rawDesc), len(file_api_proto_gomoku_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_gomoku_proto_goTypes,
		DependencyIndexes: file_api_proto_gomoku_proto_depIdxs,
		MessageInfos:      file_api_proto_gomoku_proto_msgTypes,
	}.Build()
	File_api_proto_gomoku_proto = out.File
	file_api_proto_gomoku_proto_goTypes = nil
	file_api_proto_gomoku_proto_depIdxs = nil
}
